name: Mit needs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash blah.sh

  test:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ Teste etwas"
          sleep 30

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🚀 Deploy"
          sleep 30 
